# Generated by Django 5.0 on 2026-05-01 01:59

import django.core.validators
import django.db.models.deletion
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('rutas_asignadas', models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta', verbose_name='Rutas asignadas')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda], verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso mínimo es 0.01 kg')], verbose_name='Peso (kg)')),
                ('volumen_cm3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen (cm³)')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], default='PE', max_length=2, verbose_name='Estado')),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de envío (S/.)')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_entrega_est', models.DateField(blank=True, null=True, verbose_name='Entrega estimada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Entrega real')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente', verbose_name='Destinatario')),
                ('empleado_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado', verbose_name='Registrado por')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente', verbose_name='Remitente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'db_table': 'encomiendas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], max_length=2, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DE', 'Devuelto')], max_length=2, verbose_name='Estado nuevo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='envios.empleado', verbose_name='Empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda', verbose_name='Encomienda')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'db_table': 'historial_estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
